Add query specifications
IT-Academy-Social-Projects-KRV/Logistman-Server pull request #28
Opened 2022-05-11 19:21 UTC by Grasmus

2022-05-12 09:39 UTC, Eugene-pas approved these changes

2022-05-12 10:13 UTC, Eugene-pas requested changes
Testing this push

2022-05-13 09:03 UTC, vladtymo commented on Core/Interfaces/IRepository.cs
> +        IEnumerable<TEntity> FindWithSpecification(ISpecification<TEntity> specification);
Why don't you use the async method form?

2022-05-13 10:56 UTC, closed without merging

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Services/AuthenticationService.cs
> +                .FindWithSpecification(new GetRefreshTokenByToken(userTokensDTO.RefreshToken))
Make method that return First element. Please DO NOT select all items by criteria and take first element from memory

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Interfaces/CustomService/IRoleService.cs
> +        Task<int> GetRoleByNameAsync(string name);
Already exist 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.rolemanager-1?view=aspnetcore-6.0

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Interfaces/ISpecification.cs
> +        IList<Expression<Func<TEntity, object>>> Includes { get; }
Why from Object ?
TEntity, object

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Services/GoodCategoryService.cs
> +<<<<<<< HEAD
What is it ?

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Services/GoodCategoryService.cs
> +>>>>>>> 8a83ac67acfb270be6b52f5d2140f970db84dace
Same what is this ?

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Services/OfferService.cs
> +            offer.CreatorRoleId = await _roleRepository.GetRoleByNameAsync(offerCreate.Role);
Please use [RoleManager ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.rolemanager-1?view=aspnetcore-6.0) or explain why it should not be used

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Services/RoleService.cs
> +<<<<<<< HEAD
What is it?

2022-05-13 15:34 UTC, YevheniiVovk commented on Core/Services/RoleService.cs
> +>>>>>>> 8a83ac67acfb270be6b52f5d2140f970db84dace
Same here

2022-05-13 15:34 UTC, YevheniiVovk commented
Please read about git and conflict's and before request the review of code make sure that code can be run and works !