Add entities, Fluent Api configuration, create db
IT-Academy-Social-Projects-KRV/Logistman-Server pull request #3
Opened 2022-04-18 14:29 UTC by Eugene-pas

2022-04-18 17:29 UTC, tonia4ik-s approved these changes

2022-04-18 18:13 UTC, vladtymo requested changes

2022-04-18 18:13 UTC, vladtymo commented on API/Startup.cs
> +            services
These configurations should be moved to extension method.

2022-04-18 18:13 UTC, vladtymo commented on Core/Entities/CarCategoryEntity/CarCategory.cs
> +
Remove the empty line

2022-04-18 18:13 UTC, vladtymo commented on Core/Entities/OfferEntity/Offer.cs
> +
Remove the empty line

2022-04-18 18:13 UTC, vladtymo commented on Core/Entities/PointTripEntity/PointTrip.cs
> +    public class PointTrip
You can avoid the explicit definition of intermediate table because of auto-generated many to many relationships in the EF Core.

2022-04-18 18:13 UTC, vladtymo commented on Core/Entities/PointTripEntity/PointTripConfiguration.cs
> +    public class PointTripConfiguration : IEntityTypeConfiguration<PointTrip>
Relates to the previous comment.

2022-04-18 18:13 UTC, vladtymo commented on Core/Entities/TripEntity/Trip.cs
> +        public int MaxRouteDeviation { get; set; }
What the units this field measured of?

2022-04-18 18:13 UTC, vladtymo commented on Core/Entities/TripEntity/Trip.cs
> +
Empty line...

2022-04-19 06:14 UTC, VadimChorrny approved these changes

2022-04-19 06:20 UTC, vladtymo approved these changes

2022-04-19 06:31 UTC, merged