Create email confirmation logic
IT-Academy-Social-Projects-KRV/Logistman-Server pull request #42
Opened 2022-06-03 09:41 UTC by Eugene-pas

2022-06-03 12:20 UTC, Grasmus commented on API/Controllers/AuthenticationController.cs
> +        public async Task<IActionResult> ConfirmEmail(EmailConfirmationRequestDTO request)
It will be better if asynchronous methods contain the word "Async"

2022-06-03 12:20 UTC, Grasmus commented on Core/DTO/EmailDTO/ConfirmationEmailDTO.cs
> +
Remove empty lines

2022-06-03 12:20 UTC, Grasmus commented on Core/DTO/EmailDTO/EmailConfirmationRequestDTO.cs
> +
Remove empty line

2022-06-03 12:20 UTC, Grasmus commented on Core/Helpers/AppSettings.cs
> +
Remove empty lines

2022-06-03 12:20 UTC, Grasmus commented on Core/Helpers/TemplateHelper.cs
> +            using (StringWriter sw = new StringWriter())
I think it is better to rename the sw varibale to stringWriter

2022-06-03 12:20 UTC, Grasmus commented on Core/Services/AuthenticationService.cs
> +
Remove empty line

2022-06-03 12:20 UTC, Grasmus commented on Core/Services/EmailService.cs
> +                throw new HttpException(ErrorMessages.TripNotFound, HttpStatusCode.InternalServerError);
Why do we return TripNotFound message here?

2022-06-03 15:27 UTC, marynakernychna requested changes

2022-06-03 15:27 UTC, marynakernychna commented on API/API.csproj
> +    <UserSecretsId>8630576e-1c6b-4551-8fb0-eb60a4ff1e85</UserSecretsId>
I don't think we should show such information

2022-06-03 15:27 UTC, marynakernychna commented on API/Views/ConfirmationEmail.cshtml
> +    This is a confirmation letter on the course website, if you have not done it so ignore the letter. <br /> <br />
The text of the letter does not correspond to the subject

2022-06-03 15:27 UTC, marynakernychna commented on API/appsettings.json
> +    "JWTSecret": "qUF6U9xyx943jk4TnY49nRV6WR2kRhhbwJZjRxG2Y77WnDLnPQ92aHT6jWjw9sfY3YcYsYjPHpSqZvuYd2yDK3z47n",
I don't think we should show such information

2022-06-03 15:27 UTC, marynakernychna commented on Core/Constants/StringConstants.cs
> +        public static string EmailConfirmationCallbackUrl { get; } = "https://localhost:3000/confirm-email";
Bad idea, because if we change the link to the client part, the confirmation will not work. Try extracting the link from the request, where it comes from

2022-06-03 15:27 UTC, marynakernychna commented on Core/DTO/EmailDTO/EmailConfirmationRequestDTO.cs
> +        public string Token { get; set; }
Maybe we should rename it to "ConfirmationToken"?

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/AuthenticationService.cs
> +
Delete the unnecessary empty line

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +        public EmailService(
Add empty line for separating

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +        public async Task SendConfirmationEmailAsync(User user)
Add empty line for separating

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +        public async Task SendEmailAsync(string email, string subject, string message)
Add empty line for separating

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +        public async Task ConfirmEmailAsync(EmailConfirmationRequestDTO request)
Add empty line for separating

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/UserService.cs
> +                    throw new HttpException(ErrorMessages.FailedSendEmail, HttpStatusCode.BadRequest);
The previous message was more appropriate

2022-06-03 15:27 UTC, marynakernychna commented on Core/Validation/OfferCreateValidation.cs
> -
Why did you delete this line?

2022-06-03 15:27 UTC, marynakernychna commented on Core/Validation/OfferCreateValidation.cs
>              RuleFor(offer => offer.Point)
Add empty line for separating & delete the extra line in the 31st line

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +                    Link = StringConstants.EmailConfirmationCallbackUrl + "/" + confirmationToken + "/" + user.Email
I think you should not send the user's email in the link

2022-06-03 15:27 UTC, marynakernychna commented on API/Controllers/AuthenticationController.cs
> +        public async Task<IActionResult> ConfirmEmail(EmailConfirmationRequestDTO request)
I suggest looking for a user not by email, but by id from the access token, which will be in the request header. So it will be much more securely

2022-06-03 15:27 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +            await _userManager.ConfirmEmailAsync(user, request.Token);
If the email confirmation is unsuccessful, it will return the status code 200. Do you see the problem?

2022-06-06 11:21 UTC, vladtymo commented on Core/Constants/StringConstants.cs
> +        public static string EmailConfirmationCallbackUrl { get; } = "https://localhost:3000/confirm-email";
You cal also move the client Url out to the appsettings.json file

2022-06-06 11:27 UTC, vladtymo commented on API/Startup.cs
> +            services.Configures(Configuration.GetSection("AppSettings"));
You can avoid the literal by using nameof operator

2022-06-06 11:29 UTC, vladtymo commented on API/Startup.cs
> +            services.Configures(Configuration.GetSection("AppSettings"));
You can avoid the literal by using nameof operator

2022-06-06 22:01 UTC, Grasmus commented on Core/Core.csproj
> +    <UserSecretsId>1dfe8f8d-d638-4deb-88c2-0098f9badb35</UserSecretsId>
Is it safe to store this on git?

2022-06-07 07:12 UTC, Grasmus commented on Core/Services/EmailService.cs
> +                    new HttpException(ErrorMessages.FailedSendEmail, HttpStatusCode.BadRequest);
Where is throw? Did you test this exception

2022-06-07 07:12 UTC, Grasmus commented on Core/Services/EmailService.cs
> +                new HttpException(ErrorMessages.FailedSendEmail, HttpStatusCode.BadRequest);
Where is throw? Did you test this exception

2022-06-07 07:12 UTC, Grasmus commented on Core/Validation/EmailConfirmationRequestValidation.cs
> +                .WithMessage("Token is null !");
Remove an extra space

2022-06-07 10:22 UTC, marynakernychna commented on API/Views/ConfirmationEmail.cshtml
> +<!DOCTYPE html>
Not aligned code

2022-06-07 10:22 UTC, marynakernychna commented on API/Views/ConfirmationEmail.cshtml
> +
A weird way to make text blocks separate

2022-06-07 10:22 UTC, marynakernychna commented on API/appsettings.json
> +    "EmailConfirmationCallbackUrl": "http://localhost:3000/confirm-email"
What happens if we change the link to the site or page? Try extracting the link from the request, where it comes from

2022-06-07 10:22 UTC, marynakernychna commented on Core/Entities/UserEntity/User.cs
> +        public string ConfirmEmailToken { get; set; }
I think we should make the confirmation of email in a separate entity

2022-06-07 10:22 UTC, marynakernychna commented on Core/Specifications/UserSpecification.cs
> +            public GetByConfirmToken(string token)
GetByConfirmationToken

2022-06-07 10:22 UTC, marynakernychna commented on Core/Validation/EmailConfirmationRequestValidation.cs
> +                .WithMessage("Token is null !");
FluentValidation has its messages on NotEmpty() and NotNull(), you don't need to write your own

2022-06-07 10:22 UTC, marynakernychna commented on Core/Entities/UserEntity/User.cs
> +        public string ConfirmEmailToken { get; set; }
ConfirmationEmailToken

2022-06-08 09:56 UTC, Grasmus commented on Core/Resources/ErrorMessages.resx
> +
Remove empty line

2022-06-08 09:56 UTC, Grasmus commented on Core/Services/EmailService.cs
> +                var message = await _templateHelper
Remove gaps

2022-06-08 17:08 UTC, marynakernychna commented on API/Controllers/AuthenticationController.cs
> +﻿using System;
Remove unnecessary usings

2022-06-08 17:08 UTC, marynakernychna commented on API/appsettings.json
> +
Remove the extra empty line

2022-06-08 17:08 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +                       user.ConfirmationEmailToken + "/"
Why the / in the end?

2022-06-08 17:08 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +                await SendEmailAsync(user.Email, "Confirm your account", message);
Maybe the email?

2022-06-08 17:08 UTC, marynakernychna commented on Core/Services/EmailService.cs
> +                _appSettings.SendGridSenderName);
Bracket from a new line

2022-06-08 18:06 UTC, marynakernychna approved these changes

2022-06-08 18:09 UTC, Grasmus approved these changes

2022-06-08 18:09 UTC, merged