Create Registration Endpoint
IT-Academy-Social-Projects-KRV/Logistman-Server pull request #5
Opened 2022-04-19 13:49 UTC by VadimChorrny

![image](https://user-images.githubusercontent.com/65212516/164018568-c15a150f-df1d-4831-b4e2-ce449d093104.png)

2022-04-19 15:00 UTC, tonia4ik-s reviewed
Here are a lot of parts of someone else's tasks not related with Registration endpoint and which aren't needed for registration endpoint work. Such as: jwt token (contained in many files), ErrorHandlerMiddleware (API/Middlewares/), DTOs.

2022-04-19 15:00 UTC, tonia4ik-s commented on API/Middlewares/ErrorHandlerMiddlware.cs
> +    }
Isn't registration task, so it will confict with Create exeptions task.

2022-04-19 15:00 UTC, tonia4ik-s commented on API/ServiceExtensions.cs
> +            var jwtOptions = configuration.GetSection(nameof(JwtOptions)).Get<JwtOptions>();
You don't need JWT in registration and it doesn't belong to your task.

2022-04-19 16:15 UTC, Eugene-pas requested changes

2022-04-19 16:15 UTC, Eugene-pas commented on Core/DTO/AuthenticationResultDTO.cs
> +    public class AuthenticationResultDTO
You need to put the DTO in a separate folder for each entity.

2022-04-19 16:15 UTC, Eugene-pas commented on Infrastructure/Migrations/20220419141436_init database.cs
> -    public partial class FirstMigration : Migration
You added new migrations and now everyone will have to download them, maybe it's worth deleting them? This issue will be discussed

2022-04-20 06:46 UTC, vladtymo requested changes

2022-04-20 06:46 UTC, vladtymo commented on API/Controllers/AuthenticationController.cs
> +            return Ok("Successfully created new user!");
Move the result message to resources file in order to avoid literals

2022-04-20 06:46 UTC, vladtymo commented on Core/Services/AuthenticationService.cs
> +            };
Use AutoMapper to convert DTO to Entity and vise versa

2022-04-20 07:12 UTC, vladtymo approved these changes

2022-04-20 07:20 UTC, Sergey988 approved these changes

2022-04-20 07:21 UTC, Eugene-pas approved these changes

2022-04-20 07:22 UTC, merged