Create and manage endpoint to create trip
IT-Academy-Social-Projects-KRV/Logistman-Server pull request #51
Opened 2022-06-19 14:39 UTC by Eugene-pas

2022-06-19 15:36 UTC, marynakernychna requested changes
Add an overwrite order for offers. And you can create one endpoint instead of two

2022-06-19 15:36 UTC, marynakernychna commented on Core/Interfaces/CustomService/IOfferService.cs
> +﻿using System.Collections.Generic;
Remove the extra using

2022-06-19 15:36 UTC, marynakernychna commented on Core/Services/TripService.cs
> +            trip.IsActive = true;
The trip becomes active when all participants have agreed on it

2022-06-19 15:36 UTC, marynakernychna commented on Core/Services/TripService.cs
> +            if (trip.IsActive)
You can only edit when the trip is inactive

2022-06-20 15:35 UTC, marynakernychna commented on Core/DTO/TripDTO/PointsTrip.cs
> +    public class PointsTrip
Add "DTO" at the end

2022-06-20 15:35 UTC, marynakernychna commented on Core/DTO/OfferDTO/OffersForTripDTO.cs
>          public List<int> OffersIdList { get; set; }
You don't have to add a "List" at the end

2022-06-20 15:35 UTC, marynakernychna commented on Core/Services/TripService.cs
Remove the extra empty line

2022-06-20 15:52 UTC, marynakernychna commented on Core/Services/TripService.cs
> +                    await _pointDataRepository.UpdateAsync(pointData);
Update the entire trip at once

2022-06-20 15:52 UTC, marynakernychna commented on Core/Services/TripService.cs
> +                    .RemoveAll(x => x.Id == offerId));
Why are you deleting this data?

2022-06-20 15:52 UTC, marynakernychna commented on Core/Services/TripService.cs
> +                    await _offerRepository.UpdateAsync(offer);
Update the entire trip at once

2022-06-20 15:52 UTC, marynakernychna commented on Core/Services/TripService.cs
> +                offersForTrip.OffersIdList.Remove(0);
You have already deleted

2022-06-20 15:52 UTC, marynakernychna commented on Core/Services/TripService.cs
> +                if (offersForTrip.PointsTripList.Count == 0)
You can check this at the beginning and return from this method

2022-06-20 15:52 UTC, marynakernychna commented on Core/Services/TripService.cs
> +                    trip.IsActive = false;
Are you sure?

2022-06-22 14:15 UTC, Grasmus commented on API/API.csproj
> +    <UserSecretsId>351af402-4a7b-443c-951b-8f2b9f5a7aaf</UserSecretsId>
Remove user secrete)

2022-06-22 14:15 UTC, Grasmus commented on API/Controllers/TripController.cs
> +        [HttpPost("manage-offers")]
You do not manage offers here. It's all about trip

2022-06-22 14:15 UTC, Grasmus commented on Core/DTO/OfferDTO/OffersForTripDTO.cs
> +    public class OffersForTripDTO
This DTO is using for managing trip, so I think it's better to rename it with ManageTripDTO or something

2022-06-22 14:15 UTC, Grasmus commented on Core/DTO/OfferDTO/OffersForTripDTO.cs
> +namespace Core.DTO.OfferDTO
Why is it contained in OfferDTO?

2022-06-22 14:15 UTC, Grasmus commented on Core/Services/TripService.cs
> +                        .GetByIds(points));
You already get all needed points in foreach loop, why do you do it in 162 line?

2022-06-22 14:15 UTC, Grasmus commented on Core/Specifications/TripSpecification.cs
> +                    .Include(t => t.Offers)
Why do we need this include, if we rewrite all offers by those which we get by offer ids from DTO?

2022-06-22 14:15 UTC, Grasmus commented on Core/Specifications/TripSpecification.cs
> +                    .Include(t => t.Points);
The same as for including offers

2022-06-22 16:29 UTC, Grasmus requested changes
Add validation for points order. Add check if offers load capacity valid for certain trip. Add new distance of created route. Add check if time range of offers is apropriate for certain trip.

2022-06-23 13:37 UTC, Grasmus commented on Core/DTO/TripDTO/PointsTripDTO.cs
> +﻿namespace Core.DTO.TripDTO
I think it is better to move this DTO into PointDTO namespace, because it is related to points.

2022-06-23 13:37 UTC, Grasmus commented on Core/Services/TripService.cs
> +        }
Add empty line

2022-06-23 13:37 UTC, Grasmus commented on Core/Specifications/OfferSpecification.cs
> +                                     && offer.StartDate <= expirationTrip );
Remove an extra space

2022-06-23 13:37 UTC, Grasmus commented on Core/Specifications/OfferSpecification.cs
>              }
Add empty line

2022-06-23 13:37 UTC, Grasmus commented on Core/Specifications/OfferSpecification.cs
> +                                     && offer.StartDate >= startTrip
We do not need this check

2022-06-23 13:37 UTC, Grasmus commented on Core/Validation/ManageTripValidation.cs
> +                .NotEmpty();
We do not have ids that less than zero, so we can add validation for that here

2022-06-23 13:37 UTC, Grasmus commented on Core/Validation/ManageTripValidation.cs
> +                .NotEmpty();
We should also check child entites

2022-06-23 13:37 UTC, Grasmus commented on Core/Specifications/PointDataSpecification.cs
>          }
Add empty line

2022-06-23 13:37 UTC, Grasmus commented on Core/Specifications/OfferSpecification.cs
> +        }
Add empty line

2022-06-23 13:37 UTC, Grasmus commented on Core/Services/TripService.cs
> +            if (!trip.IsActive)
Why don`t we check if trip is active at the begining?

2022-06-23 13:40 UTC, Grasmus commented on Core/Specifications/TripSpecification.cs
> +                                 && !t.IsEnded
We should also check if trip is not active

2022-06-24 12:32 UTC, Grasmus commented on Core/Services/TripService.cs
> +
Remove empty line

2022-06-24 12:32 UTC, Grasmus commented on Core/Services/TripService.cs
> +
Remove empty line

2022-06-24 12:32 UTC, Grasmus commented on Core/Services/TripService.cs
> +            trip.Distance = manageTrip.Distance;
Add empty line

2022-06-24 12:32 UTC, Grasmus commented on Core/Validation/OfferIdsValidation.cs
> +                .WithMessage("Offer Id must be greater than 0!");
Such message will appear automatically

2022-06-24 16:53 UTC, Grasmus commented on Core/Specifications/TripSpecification.cs
> +            }
Add empty line

2022-06-27 19:31 UTC, Grasmus approved these changes

2022-06-29 17:06 UTC, marynakernychna commented on API/Controllers/TripController.cs
> +        [HttpPost("manage-trip")]
You can entitle the endpoint like "manage"

2022-06-29 17:06 UTC, marynakernychna commented on Core/DTO/TripDTO/ManageTripDTO.cs
> +﻿using System;
Delete the extra using

2022-06-29 17:06 UTC, marynakernychna commented on Core/Interfaces/CustomService/IPointService.cs
> +        List<PointsTripDTO> SortByOrder(List<PointsTripDTO> points);
We already have this method, you just need to make it generalized and use it freely

2022-06-29 17:06 UTC, marynakernychna commented on Core/Interfaces/CustomService/ITripValidationService.cs
> +            List<int> offerIds,
I belive it would be more correct to write "offersIds"

2022-06-29 17:06 UTC, marynakernychna commented on Core/Interfaces/CustomService/ITripValidationService.cs
> +            DateTimeOffset expirationTrip);
Maybe "tripStartDate" & "tripExpirationDate"? I belive it would be more correct. So it will be clear what type these fields have

2022-06-29 17:06 UTC, marynakernychna commented on Core/Interfaces/CustomService/ITripValidationService.cs
> +            DateTimeOffset expirationDate,
The same remark as in lines 12 & 13

2022-06-29 17:06 UTC, marynakernychna commented on Core/Interfaces/CustomService/ITripValidationService.cs
> +
We do not write blank lines between declarations of methods

2022-06-29 17:06 UTC, marynakernychna commented on Core/Interfaces/CustomService/ITripValidationService.cs
> +        Task ValidOffersCheckAsync(
So, "Valid..." or "Validate..." ? You call the methods differently

2022-06-29 17:06 UTC, marynakernychna commented on Core/Services/InviteService.cs
> -            var trip = await _tripRepository
You forgot to remove this field (_tripRepository) from this service

2022-06-29 17:06 UTC, marynakernychna commented on Core/Services/InviteService.cs
> -                var offer = await _offerRepository
You forgot to remove this field (_offerRepository) from this service

2022-06-29 17:06 UTC, marynakernychna commented on Core/Services/TripService.cs
> +            ExceptionMethods.TripNullCheck(trip);
I believe you should first check if there is the trip exists, and then the points.
Because, firstly, the trip is higher in the hierarchy, and secondly, checking the trip will take less time than checking the points

2022-06-29 17:06 UTC, marynakernychna commented on Core/Services/TripService.cs
> +            foreach (var pointTrip in sortedPoints)
Maybe "tripPoint" or just "point" ?

2022-06-29 17:06 UTC, marynakernychna commented on Core/Specifications/PointDataSpecification.cs
> +            public GetByIds(List<int> pointIds)
Maybe "pointsIds" ?

2022-06-29 17:06 UTC, marynakernychna commented on Core/Specifications/TripSpecification.cs
>              }
The name does not correspond to the full reality, here not only extraction by id, but also many other checks

2022-06-29 17:06 UTC, marynakernychna commented on Core/Validation/PiontTripValidation.cs
> +        public PiontTripValidation()
Entitle it to "PiontTripValidation"

2022-06-30 12:26 UTC, Grasmus commented on Core/Validation/PiontTripValidation.cs
> +        public PiontTripValidation()
You mean "PointTripValidation"?

2022-06-30 12:28 UTC, Grasmus commented on Core/Interfaces/CustomService/IPointService.cs
> +        List<PointsTripDTO> SortByOrder(List<PointsTripDTO> points);
We cannot generalize it, because it uses different DTOs, which aren`t related to each other

2022-07-02 13:54 UTC, Grasmus commented on Core/DTO/OfferDTO/OfferCreateTripDTO.cs
> +        public int key { get; set; }
We write properties with capitalize first letter

2022-07-03 19:48 UTC, marynakernychna approved these changes

2022-07-03 19:48 UTC, merged