Feat/dv 136/create endpoint to confirm goods delivery
IT-Academy-Social-Projects-KRV/Logistman-Server pull request #67
Opened 2022-07-13 15:07 UTC by Grasmus

2022-07-15 17:03 UTC, AndriiChepeliuk approved these changes

2022-07-16 21:08 UTC, marynakernychna requested changes
If the driver presses the button before any of the senders or receivers, then we never run out of trip

2022-07-16 21:08 UTC, marynakernychna commented on API/Controllers/OfferController.cs
> +        public async Task<IActionResult> ConfirmGoodsTransferAsync([FromBody] ConfirmGoodsTransferDTO confirmGoodsTransferDTO)
Move the parameter to a new line

2022-07-16 21:08 UTC, marynakernychna commented on Core/DTO/OfferDTO/ConfirmGoodsTransferDTO.cs
> +        public OfferIdDTO OfferIdDTO { get; set; }
Why don't you just write a field?

2022-07-16 21:08 UTC, marynakernychna commented on Core/Interfaces/CustomService/IOfferService.cs
> +        Task ConfirmGoodsTransferAsync(ConfirmGoodsTransferDTO confirmGoodTransferDTO, string userId);
Move the parameter to a new line & also in the whole file

2022-07-16 21:08 UTC, marynakernychna commented on Core/Resources/ErrorMessages.resx
> +
Remove the extra blank line

2022-07-16 21:08 UTC, marynakernychna commented on Core/Services/OfferService.cs
> +                    .GetByIdWithActiveTrip(сonfirmGoodsTransferDTO.OfferIdDTO.OfferId));
Add a tab before calling the specification to better understand the level of nesting. Do this for the entire file as well

2022-07-16 21:08 UTC, marynakernychna commented on Core/Services/OfferService.cs
> +            if (сonfirmGoodsTransferDTO.TripRole.ToUpper() == Constants.TripRoles.Driver)
You can use "switch", it'll work faster

2022-07-16 21:08 UTC, marynakernychna commented on Core/Specifications/OfferSpecification.cs
> +                    && !o.IsAnsweredByDriver)
Add a tab before new conditions to better understand the level of nesting. Do this for the entire file as well

2022-07-16 21:08 UTC, marynakernychna commented on Core/Services/OfferService.cs
> +                if (offer.Trip.TripCreatorId != userId)
Why don't you check this right away in the specification?

2022-07-16 21:08 UTC, marynakernychna commented on Core/Specifications/OfferSpecification.cs
> +        public class GetByIdWithActiveTrip : Specification<Offer>, ISingleResultSpecification<Offer>
Move the inheritance from the second interface to a new line

2022-07-16 21:08 UTC, marynakernychna commented on Core/Specifications/TripSpecification.cs
> +        internal class GetActiveByUserIdWithOffers : Specification<Trip>, ISingleResultSpecification<Trip>
Move the imitation from the second interface to a new line

2022-07-17 14:27 UTC, tonia4ik-s approved these changes

2022-07-17 15:58 UTC, marynakernychna approved these changes

2022-07-17 16:00 UTC, merged